"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
var inversify_1 = require("inversify");
var eventManager_1 = require("./eventManager");
var localStorageData_1 = require("./localStorageData");
var logger_1 = require("./logger");
var restClient_1 = require("./restClient");
var authenticatedRestClient_1 = require("./authenticatedRestClient");
var sessionManager_1 = require("./sessionManager");
var webSocketManager_1 = require("./webSocketManager");
var networkManager_1 = require("./networkManager");
var deviceManager_1 = require("./deviceManager");
var facebookManager_1 = require("./facebookManager");
var conversationManager_1 = require("./conversationManager");
var profileManager_1 = require("./profileManager");
var messageManager_1 = require("./messageManager");
var container = new inversify_1.Container();
exports.container = container;
container.bind("EventManager").to(eventManager_1.EventManager).inSingletonScope();
container.bind("LocalStorageData").to(localStorageData_1.LocalStorageData);
container.bind("Logger").to(logger_1.Logger);
container.bind("RestClient").to(restClient_1.RestClient);
container.bind("SessionManager").to(sessionManager_1.SessionManager).inSingletonScope();
container.bind("WebSocketManager").to(webSocketManager_1.WebSocketManager);
container.bind("NetworkManager").to(networkManager_1.NetworkManager);
container.bind("AuthenticatedRestClient").to(authenticatedRestClient_1.AuthenticatedRestClient);
container.bind("DeviceManager").to(deviceManager_1.DeviceManager);
container.bind("FacebookManager").to(facebookManager_1.FacebookManager);
container.bind("ConversationManager").to(conversationManager_1.ConversationManager);
container.bind("ProfileManager").to(profileManager_1.ProfileManager);
container.bind("MessageManager").to(messageManager_1.MessageManager);
//# sourceMappingURL=inversify.config.js.map